AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, prod]

Globals:
  Function:
    Runtime: python3.12
    Timeout: 10
    AutoPublishAlias: live  # 关键：自动发布新版本并更新别名

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Events:
        Api:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      DeploymentPreference:
        Type: Canary10Percent5Minutes  # 蓝绿策略（可选：Linear10PercentEvery1Minute, AllAtOnce）
        Alarms:
          - !Ref HelloWorldErrorsAlarm
        Hooks:
          PreTraffic: !GetAtt PreTrafficFunction.Arn
          PostTraffic: !GetAtt PostTrafficFunction.Arn

  # 预流量 Hook（部署前验证）
  PreTrafficFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: hooks.pre_traffic_hook
      Runtime: python3.12
      Environment:
        Variables:
          PRIMARY_FUNCTION_VERSION: !Ref HelloWorldFunction.Version

  # 后流量 Hook（部署后验证）
  PostTrafficFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: hooks.post_traffic_hook
      Runtime: python3.12

  # CloudWatch 告警（用于自动回滚）
  HelloWorldErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-HelloWorld-Errors"
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60
      Statistic: Sum
      Threshold: 1
      Dimensions:
        - Name: FunctionName
          Value: !Ref HelloWorldFunction
